### PR TITLE
client: fix foreman parameters conversion

### LINKED ISSUE #76: Error setting host parameters - SDK upgrade related?
Hi,

Latest master errors when attempting to create a host with a host parameter, eg:
```
resource "foreman_host" "example" {
  name               = "test_host"
  parameters = {
    test_param = "test"
  }
}
```
```
│ Error: HTTP Error:{
│   endpoint:   [https://uk1sxlx00219.corpnet2.com/api/hosts]
│   statusCode: [422]
│   respBody:   [{
│   "error": {"id":null,"errors":{"host_parameters.name":["can't be blank"]},"full_messages":["Name can't be blank"]}
│ }
│ ]
│ }
```
Released version (v4.5) works fine.
Again, might be related to the [SDK upgrade](https://github.com/HanseMerkur/terraform-provider-foreman/pull/69).

Cheers.

### PR DESCRIPTION
**Pull request by MrFreezeex**
make() was allocating empty parameters and then we were adding the real
entries after those empty one. In this commit we simply remove make and
construct the slice dynamically with append.

Signed-off-by: Arthur Outhenin-Chalandre <arthur.outhenin-chalandre@cern.ch>

Fixes #76

### CODE REVIEW

File: foreman/api/client.go [hunk 1]
```diff
@@ -82,16 +82,13 @@ type ForemanKVParameter struct {
 }
 
 func FromKV(kv []ForemanKVParameter) (ret map[string]string) {
-	ret = make(map[string]string)
```
Comment (lhw) [inline foreman/api/client.go:85]: This shouldn't work. A map without make() is nil and no entry can be added.

File: foreman/api/client.go [hunk 2]
```diff
@@ -82,16 +82,13 @@ type ForemanKVParameter struct {
...
 	for _, pair := range kv {
 		ret[pair.Name] = pair.Value
 	}
 	return ret
 }
 
 func ToKV(m map[string]interface{}) (ret []ForemanKVParameter) {
-	ret = make([]ForemanKVParameter, len(m))
-
```
Comment (lhw) [inline foreman/api/client.go:94]: Yeah my bad. I copy and pasted in the append lines below so I didn't think about this issue. Of course this will add len(m) empty entries and then append the real ones

**Review by lhw — CHANGES_REQUESTED** [review]
The second one is the issue. The first change will introduce a bug
